### Broadcasting

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1 = arr/10
arr1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [4]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
slice_arr = arr[0:6]

In [7]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
slice_arr[:] = 555

In [9]:
slice_arr

array([555, 555, 555, 555, 555, 555])

In [10]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [11]:
arr_copy = arr.copy()

In [12]:
arr_copy[:] = 1000

In [13]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [14]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

### Conditional Selection 

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
boo_arr = arr>4

In [17]:
boo_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [18]:
arr[boo_arr]

array([5, 6, 7, 8, 9])

In [19]:
arr[arr>4]

array([5, 6, 7, 8, 9])

### Arithmetic

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [24]:
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [25]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### Universal Array Functions

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [28]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [29]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### List Vs Numpy

In [30]:
size = 100

In [31]:
x1 = range(size)
y1 = range(size)

In [32]:
x1

range(0, 100)

In [33]:
%%timeit
for i in range(size):
   x1[i]*y1[i] 

74 µs ± 4.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
x2 = np.arange(size)
y2 = np.arange(size)

In [35]:
%%timeit
x2*y2

2.23 µs ± 85.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Append

In [37]:
a_row = np.append(a,[[21,22,23]],axis=0)
a_row

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23]])

In [38]:
a_col = np.array([34,35,36]).reshape(3,1)
a_col


array([[34],
       [35],
       [36]])

In [39]:
a_coll = np.append(a,a_col,axis=1)

In [40]:
a_coll

array([[ 1,  2,  3, 34],
       [ 4,  5,  6, 35],
       [ 7,  8,  9, 36]])

### Insert 

In [41]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
b_ins = np.insert(b,1,[15,13,12],axis=0)

In [44]:
b_ins

array([[ 1,  2,  3],
       [15, 13, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [45]:
b_ins2 = np.insert(b,1,[15,13,12],axis=1)

In [46]:
b_ins2

array([[ 1, 15,  2,  3],
       [ 4, 13,  5,  6],
       [ 7, 12,  8,  9]])

### Matrix

In [47]:
x = np.matrix('1,2,3;4,5,6;7,8,9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x.shape

(3, 3)

In [49]:
x.size

9

In [50]:
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x[2,1] = -7

In [52]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [53]:
x[1,:]

matrix([[4, 5, 6]])

#### &&&&&